spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: <your_email>@gmail.com # Email as sender
    password: <app_password> # Generate here https://myaccount.google.com/apppasswords
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true